"""Alembic helpers wired for async SQLAlchemy engines.

Business projects scaffolded by ``hwhkit init`` (W5) get a ``migrations/``
directory with ``env.py`` that imports from this module. For bare ``hwhkit``
usage (no scaffolder), the same helpers can be called directly from a
hand-written ``env.py``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncEngine


def run_migrations_online(
    engine: AsyncEngine,
    target_metadata: Any = None,
    **context_kwargs: Any,
) -> None:
    """Run alembic migrations against an async engine.

    Used by the project ``env.py``:

        from hwhkit.integrations.postgres.migrations import run_migrations_online
        run_migrations_online(my_engine, target_metadata=Base.metadata)
    """
    import asyncio

    from alembic import context

    async def _do_run_async_migrations(connection: Any) -> None:
        def _do_run_sync(sync_connection: Any) -> None:
            context.configure(
                connection=sync_connection,
                target_metadata=target_metadata,
                **context_kwargs,
            )
            with context.begin_transaction():
                context.run_migrations()

        # connection is an AsyncConnection; run_sync calls the sync fn on it
        await connection.run_sync(_do_run_sync)

    async def _do_run() -> None:
        async with engine.connect() as connection:
            await _do_run_async_migrations(connection)
        await engine.dispose()

    asyncio.run(_do_run())


def run_migrations_offline(
    url: str,
    target_metadata: Any = None,
    **context_kwargs: Any,
) -> None:
    """Generate SQL without connecting (alembic ``--sql`` mode)."""
    from alembic import context

    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **context_kwargs,
    )
    with context.begin_transaction():
        context.run_migrations()


# Template snippet that ``hwhkit add postgres`` (W5) will write to
# ``migrations/env.py`` of the user's project. Kept here as a module
# attribute so the scaffolder doesn't re-implement the snippet.
ENV_PY_TEMPLATE = '''"""Alembic environment — generated by hwhkit add postgres."""

from __future__ import annotations

import os

from alembic import context
from sqlalchemy.ext.asyncio import create_async_engine

from hwhkit.integrations.postgres.migrations import (
    run_migrations_offline,
    run_migrations_online,
)

# Replace with your project's Base.metadata
target_metadata = None

DSN = os.environ.get("HWHKIT_POSTGRES__DSN", "postgresql+asyncpg://postgres:postgres@localhost/postgres")

if context.is_offline_mode():
    run_migrations_offline(DSN, target_metadata=target_metadata)
else:
    engine = create_async_engine(DSN, future=True)
    run_migrations_online(engine, target_metadata=target_metadata)
'''


__all__ = ["ENV_PY_TEMPLATE", "run_migrations_offline", "run_migrations_online"]
